### ISSUE TITLE
Allow for different font-display descriptors for different at-rules

### ISSUE THREAD

**Issue by galvarez421** [dkrnl/postcss-font-display#3]
Hi, would you accept a pull request to extend the current functionality so that an array of configuration objects can be passed, each with a new `test` property that allows you to specify which font families the configuration should apply to? This would allow for configuring different `font-display` descriptors to be used for different `@font-face` at-rules. For example, the plugin could be initialized as follows:

```
postcss([require('postcss-font-display')(
  [
    {
      test: true,
      display: 'swap',
    },
    // See https://github.com/FortAwesome/Font-Awesome/issues/14387#issuecomment-567093531
    {
      test: ['FontAwesome'], // or 'FontAwesome'
      display: 'block',
    },
  ]
)])
```
I have implemented this modification locally for a project and it works as expected. According to the implementation:

- `test` can be one of the following
  - `true`: Match all @font-face at-rules
  - {string}: Match only @font-face at-rules containing provided font-family value
  - {array of strings}: Match only @font-face at-rules containing at least one of the provided font-family values
- `test` can be used even if a single object is used for configuration instead of an array of objects. The default value is `true` to match the current behavior.
- Each configuration object is merged with a default configuration object.
- If an at-rule matches multiple tests, the applicable configuration objects are merged, with configuration objects with higher indices taking precedence.

I would be happy to submit a pull request. Thank you.

**Comment by dkrnl** [comment]
Hi!
Thx for idea. New in v0.2.1 version:
```js
postcss([ require('postcss-font-display')([
  { display: 'swap', replace: false },
  { test: 'FontAwesome', display: 'block' },
]) ])
```
